In [7]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Ujjwala","19","Kakinada"])
    writer.writerow(["Laya","26","Hyderabad"])

In [9]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Ujjwala', '19', 'Kakinada']
['Laya', '26', 'Hyderabad']


In [11]:
import numpy as np

In [13]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
l=range(1000)
%timeit [i**2 for i in l]

173 μs ± 11.8 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [19]:
a=np.arange(1000)
%timeit a**2

2.31 μs ± 271 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating arrays

In [22]:
a=np.array([1,2,3,4]) #one dimensional array or vectors

In [24]:
print(a.ndim)

1


In [26]:
b=np.array([[1,2,3],[4,5,5]]) #two dimensional array or matrix
print(b)

[[1 2 3]
 [4 5 5]]


In [28]:
print(b.ndim)

2


In [30]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #3 dimensional (in cube)
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3


In [32]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


# functions for creating array

In [35]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [39]:
#using linspace
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [41]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [49]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [51]:
print(np.diag(a))

[1 2 3 4]


# Basic data types

In [54]:
a=np.arange(10)
print(a.dtype)

int32


In [56]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [58]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# other data types

In [61]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [63]:
a=np.array([True,False])
print(a.dtype)

bool


In [67]:
a=np.array(["Aditya degree College"])
print(a.dtype) #unicode string type

<U21


# Indexing and slicing

In [70]:
a=np.arange(10)
print(a[5])

5


In [72]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [74]:
print(a[0,0])

1


In [76]:
b=np.arange(1,10)
print(b[2:5])

[3 4 5]


# slicing

In [79]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
print(a[1:8:3])

[1 4 7]


In [83]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [85]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [87]:
a[1,1]=5
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 3]]


In [89]:
a=np.arange(10)
a[4:]=9
a

array([0, 1, 2, 3, 9, 9, 9, 9, 9, 9])

# copying and viewing

In [92]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [94]:
print(np.shares_memory(a,b))

True


In [96]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [98]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [100]:
print(np.shares_memory(a,b))

False


In [102]:
print(b.base)

None


# Random number generator

In [105]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)

[ 8 15 11  4  5  7 18  7  0 12  2 17  1  7  7]


In [107]:
mask=(a%2==0)
new_a=a[mask]
print(new_a)

[ 8  4 18  0 12  2]


In [109]:
a[mask]=-1
print(a)

[-1 15 11 -1  5  7 -1  7 -1 -1 -1 17  1  7  7]


# Element wise operation
1. Basic operation

In [113]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [115]:
print(a**2)

[ 1  4  9 16]


# All arithmetic operates element wise

In [118]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [120]:
print(a*b)

[2. 4. 6. 8.]


In [122]:
c=np.diag([1,2,3,4])
print(c)
print(c *c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [124]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision operator

In [127]:
a=np.array([1,2,6])
b=np.array([4,5,6])
print(a==b)

[False False  True]


In [129]:
print(a<b)

[ True  True False]


In [131]:
print(a>b)

[False False False]


In [133]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))

True


# logical operator

In [136]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [138]:
print(np.logical_and(a,b))

[ True False False False]


In [140]:
print(np.logical_not(a))

[False  True False  True]


# trignomerty/ transcendental functions

In [143]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [145]:
print(np.sin(a))

[0.         0.84147098 0.90929743 0.14112001]


In [149]:
np.log(a)

C:\Users\admin\AppData\Local\Temp\ipykernel_8016\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])